[2025-05-19T09:07:32.230+0000] {processor.py:186} INFO - Started process (PID=105) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:07:32.238+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:07:32.290+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:07:32.286+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:07:33.464+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:07:33.267+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 2, in <module>
    from airflow.operators.python import PythonOperatr
ImportError: cannot import name 'PythonOperatr' from 'airflow.operators.python' (/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py)
[2025-05-19T09:07:33.541+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:07:33.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 1.797 seconds
[2025-05-19T09:08:29.251+0000] {processor.py:186} INFO - Started process (PID=173) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:08:29.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:08:29.263+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:08:29.262+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:08:29.420+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:08:29.417+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 17
    dag   = DAG(
               ^
SyntaxError: '(' was never closed
[2025-05-19T09:08:29.423+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:08:29.483+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.248 seconds
[2025-05-19T09:08:40.426+0000] {processor.py:186} INFO - Started process (PID=203) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:08:40.430+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:08:40.441+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:08:40.440+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:08:40.845+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:08:40.824+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 20
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 20)
[2025-05-19T09:08:40.870+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:08:41.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.629 seconds
[2025-05-19T09:08:44.336+0000] {processor.py:186} INFO - Started process (PID=208) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:08:44.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:08:44.449+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:08:44.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:08:44.745+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:08:44.741+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 20
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 20)
[2025-05-19T09:08:44.748+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:08:44.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.640 seconds
[2025-05-19T09:08:47.923+0000] {processor.py:186} INFO - Started process (PID=214) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:08:47.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:08:47.965+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:08:47.954+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:08:48.312+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:08:48.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 20
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 20)
[2025-05-19T09:08:48.322+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:08:48.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.652 seconds
[2025-05-19T09:09:26.368+0000] {processor.py:186} INFO - Started process (PID=279) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:09:26.373+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:09:26.384+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:09:26.383+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:09:26.833+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:09:26.830+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 20
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 20)
[2025-05-19T09:09:26.846+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:09:26.970+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.632 seconds
[2025-05-19T09:09:57.620+0000] {processor.py:186} INFO - Started process (PID=347) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:09:57.623+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:09:57.630+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:09:57.629+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:09:57.718+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:09:57.715+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 20
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 20)
[2025-05-19T09:09:57.721+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:09:57.772+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.169 seconds
[2025-05-19T09:10:27.999+0000] {processor.py:186} INFO - Started process (PID=414) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:10:28.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:10:28.009+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:10:28.008+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:10:28.101+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:10:28.098+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 20
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 20)
[2025-05-19T09:10:28.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:10:28.164+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.180 seconds
[2025-05-19T09:10:58.521+0000] {processor.py:186} INFO - Started process (PID=481) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:10:58.527+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:10:58.536+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:10:58.535+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:10:58.979+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:10:58.976+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 20
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 20)
[2025-05-19T09:10:58.983+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:10:59.047+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.547 seconds
[2025-05-19T09:11:30.183+0000] {processor.py:186} INFO - Started process (PID=549) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:11:30.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:11:30.216+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:11:30.215+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:11:30.437+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:11:30.429+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 20
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 20)
[2025-05-19T09:11:30.441+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:11:30.529+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.366 seconds
[2025-05-19T09:12:01.376+0000] {processor.py:186} INFO - Started process (PID=616) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:12:01.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:12:01.420+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:12:01.419+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:12:01.782+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:12:01.776+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 20
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 20)
[2025-05-19T09:12:01.787+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:12:01.892+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.539 seconds
[2025-05-19T09:12:32.792+0000] {processor.py:186} INFO - Started process (PID=691) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:12:32.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:12:32.798+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:12:32.798+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:12:32.833+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:12:32.832+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 20
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 20)
[2025-05-19T09:12:32.834+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:12:32.867+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.085 seconds
[2025-05-19T09:13:03.563+0000] {processor.py:186} INFO - Started process (PID=759) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:13:03.565+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:13:03.571+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:13:03.570+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:13:03.632+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:13:03.630+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 20
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 20)
[2025-05-19T09:13:03.633+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:13:03.670+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.117 seconds
[2025-05-19T09:13:34.453+0000] {processor.py:186} INFO - Started process (PID=826) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:13:34.460+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:13:34.470+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:13:34.469+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:13:34.881+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:13:34.876+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 20
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 20)
[2025-05-19T09:13:34.893+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:13:34.991+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.560 seconds
[2025-05-19T09:13:43.996+0000] {processor.py:186} INFO - Started process (PID=841) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:13:43.999+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:13:44.006+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:13:44.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:13:44.133+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:13:44.131+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 20
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 20)
[2025-05-19T09:13:44.136+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:13:44.192+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.211 seconds
[2025-05-19T09:14:10.664+0000] {processor.py:186} INFO - Started process (PID=897) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:14:10.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:14:10.676+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:14:10.675+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:14:11.004+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:14:10.995+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 20
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 20)
[2025-05-19T09:14:11.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:14:11.094+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.447 seconds
[2025-05-19T09:14:41.421+0000] {processor.py:186} INFO - Started process (PID=965) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:14:41.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:14:41.427+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:14:41.427+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:14:41.488+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:14:41.486+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 20
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 20)
[2025-05-19T09:14:41.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:14:41.543+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.134 seconds
[2025-05-19T09:14:52.582+0000] {processor.py:186} INFO - Started process (PID=991) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:14:52.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:14:52.592+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:14:52.591+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:14:52.641+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:14:52.639+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 22
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 22)
[2025-05-19T09:14:52.643+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:14:52.686+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.117 seconds
[2025-05-19T09:15:03.977+0000] {processor.py:186} INFO - Started process (PID=1021) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:03.979+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:15:03.986+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:15:03.986+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:04.049+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:15:04.047+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 22
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 22)
[2025-05-19T09:15:04.051+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:04.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.127 seconds
[2025-05-19T09:15:17.345+0000] {processor.py:186} INFO - Started process (PID=1041) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:17.358+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:15:17.371+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:15:17.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:17.979+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:15:17.974+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 23
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-19T09:15:17.993+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:18.153+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.829 seconds
[2025-05-19T09:15:22.056+0000] {processor.py:186} INFO - Started process (PID=1047) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:22.059+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:15:22.070+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:15:22.068+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:22.407+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:15:22.402+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 23
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-19T09:15:22.415+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:22.493+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.461 seconds
[2025-05-19T09:15:25.536+0000] {processor.py:186} INFO - Started process (PID=1058) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:25.540+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:15:25.547+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:15:25.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:25.682+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:15:25.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 23
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-19T09:15:25.686+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:25.750+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.229 seconds
[2025-05-19T09:15:44.178+0000] {processor.py:186} INFO - Started process (PID=1104) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:44.181+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:15:44.188+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:15:44.187+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:44.320+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:15:44.318+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 23
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-19T09:15:44.323+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:44.376+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.212 seconds
[2025-05-19T09:15:48.205+0000] {processor.py:186} INFO - Started process (PID=1110) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:48.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:15:48.230+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:15:48.229+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:49.117+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:15:49.109+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 23
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-19T09:15:49.155+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:15:49.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 1.090 seconds
[2025-05-19T09:16:20.027+0000] {processor.py:186} INFO - Started process (PID=1177) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:16:20.031+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:16:20.041+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:16:20.040+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:16:20.203+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:16:20.200+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 23
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-19T09:16:20.207+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:16:20.321+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.312 seconds
[2025-05-19T09:16:24.686+0000] {processor.py:186} INFO - Started process (PID=1184) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:16:24.690+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:16:24.700+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:16:24.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:16:24.902+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:16:24.898+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 23
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 23)
[2025-05-19T09:16:24.905+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:16:24.991+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.327 seconds
[2025-05-19T09:16:30.528+0000] {processor.py:186} INFO - Started process (PID=1200) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:16:30.532+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:16:30.543+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:16:30.542+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:16:30.742+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:16:30.739+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 24
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 24)
[2025-05-19T09:16:30.745+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:16:30.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.331 seconds
[2025-05-19T09:16:37.193+0000] {processor.py:186} INFO - Started process (PID=1217) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:16:37.201+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:16:37.216+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:16:37.215+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:16:37.460+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:16:37.457+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:16:37.464+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:16:37.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.439 seconds
[2025-05-19T09:16:43.288+0000] {processor.py:186} INFO - Started process (PID=1230) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:16:43.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:16:43.298+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:16:43.297+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:16:43.434+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:16:43.431+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:16:43.437+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:16:43.493+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.220 seconds
[2025-05-19T09:17:13.661+0000] {processor.py:186} INFO - Started process (PID=1298) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:17:13.664+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:17:13.670+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:17:13.669+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:17:13.823+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:17:13.821+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:17:13.826+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:17:13.872+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.222 seconds
[2025-05-19T09:17:24.347+0000] {processor.py:186} INFO - Started process (PID=1319) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:17:24.351+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:17:24.358+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:17:24.357+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:17:24.472+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:17:24.470+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:17:24.475+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:17:24.530+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.199 seconds
[2025-05-19T09:17:26.336+0000] {processor.py:186} INFO - Started process (PID=1321) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:17:26.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:17:26.347+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:17:26.346+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:17:26.491+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:17:26.488+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:17:26.494+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:17:26.551+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.229 seconds
[2025-05-19T09:17:42.695+0000] {processor.py:186} INFO - Started process (PID=1362) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:17:42.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:17:42.705+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:17:42.704+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:17:42.768+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:17:42.766+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:17:42.770+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:17:42.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.142 seconds
[2025-05-19T09:18:13.842+0000] {processor.py:186} INFO - Started process (PID=1431) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:18:13.847+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:18:13.854+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:18:13.853+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:18:13.989+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:18:13.987+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:18:13.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:18:14.048+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.220 seconds
[2025-05-19T09:18:35.070+0000] {processor.py:186} INFO - Started process (PID=1477) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:18:35.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:18:35.109+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:18:35.107+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:18:35.412+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:18:35.407+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:18:35.415+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:18:35.527+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.549 seconds
[2025-05-19T09:18:37.535+0000] {processor.py:186} INFO - Started process (PID=1481) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:18:37.539+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:18:37.547+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:18:37.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:18:37.800+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:18:37.796+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:18:37.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:18:37.917+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.400 seconds
[2025-05-19T09:19:09.449+0000] {processor.py:186} INFO - Started process (PID=1547) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:19:09.462+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:19:09.477+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:19:09.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:19:09.903+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:19:09.898+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:19:09.912+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:19:10.023+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.606 seconds
[2025-05-19T09:19:40.790+0000] {processor.py:186} INFO - Started process (PID=1615) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:19:40.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:19:40.800+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:19:40.800+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:19:40.926+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:19:40.923+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:19:40.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:19:40.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.213 seconds
[2025-05-19T09:19:47.925+0000] {processor.py:186} INFO - Started process (PID=1628) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:19:47.930+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:19:47.939+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:19:47.938+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:19:48.093+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:19:48.090+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:19:48.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:19:48.148+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.238 seconds
[2025-05-19T09:20:18.305+0000] {processor.py:186} INFO - Started process (PID=1696) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:20:18.308+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:20:18.314+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:20:18.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:20:18.384+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:20:18.381+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:20:18.386+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:20:18.427+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.137 seconds
[2025-05-19T09:20:45.957+0000] {processor.py:186} INFO - Started process (PID=1753) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:20:45.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:20:45.966+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:20:45.966+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:20:46.218+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:20:46.207+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:20:46.221+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:20:46.310+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.377 seconds
[2025-05-19T09:21:17.038+0000] {processor.py:186} INFO - Started process (PID=1820) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:21:17.041+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:21:17.048+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:21:17.048+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:21:17.165+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:21:17.163+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:21:17.168+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:21:17.216+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.199 seconds
[2025-05-19T09:21:21.813+0000] {processor.py:186} INFO - Started process (PID=1832) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:21:21.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:21:21.829+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:21:21.828+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:21:22.138+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:21:22.134+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:21:22.143+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:21:22.240+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.449 seconds
[2025-05-19T09:21:52.425+0000] {processor.py:186} INFO - Started process (PID=1899) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:21:52.427+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:21:52.432+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:21:52.431+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:21:52.516+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:21:52.514+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:21:52.518+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:21:52.561+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.148 seconds
[2025-05-19T09:22:23.580+0000] {processor.py:186} INFO - Started process (PID=1966) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:22:23.586+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:22:23.594+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:22:23.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:22:23.737+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:22:23.735+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:22:23.740+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:22:23.788+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.221 seconds
[2025-05-19T09:26:12.319+0000] {processor.py:186} INFO - Started process (PID=95) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:26:12.329+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:26:12.346+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:26:12.344+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:26:12.589+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:26:12.584+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:26:12.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:26:12.724+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.430 seconds
[2025-05-19T09:43:37.716+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:43:37.720+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:43:37.729+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:43:37.728+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:43:37.805+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:43:37.802+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:43:37.810+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:43:37.890+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.193 seconds
[2025-05-19T09:44:08.640+0000] {processor.py:186} INFO - Started process (PID=225) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:44:08.642+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:44:08.647+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:44:08.646+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:44:08.704+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:44:08.702+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:44:08.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:44:08.744+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.116 seconds
[2025-05-19T09:44:40.393+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:44:40.395+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/__pycache__/docket_launch_2.py for tasks to queue
[2025-05-19T09:44:40.399+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:44:40.398+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:44:40.456+0000] {logging_mixin.py:190} INFO - [2025-05-19T09:44:40.454+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/__pycache__/docket_launch_2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/__pycache__/docket_launch_2.py", line 25
    schedule_interval = None',
                            ^
SyntaxError: unterminated string literal (detected at line 25)
[2025-05-19T09:44:40.458+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/__pycache__/docket_launch_2.py
[2025-05-19T09:44:40.503+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/__pycache__/docket_launch_2.py took 0.121 seconds
